#!/bin/bash

go test -race -run TestBasic1
go test -race -run TestBasic2
go test -race -run TestBasic3
go test -race -run TestBasic4
go test -race -run TestBasic5
go test -race -run TestBasic6
go test -race -run TestBasic7
go test -race -run TestBasic8
go test -race -run TestBasic9
go test -race -run TestSendReceive1
go test -race -run TestSendReceive2
go test -race -run TestSendReceive3
go test -race -run TestRobust1
go test -race -run TestRobust2
go test -race -run TestRobust3
go test -race -run TestRobust4
go test -race -run TestRobust5
go test -race -run TestRobust6
go test -race -run TestExpBackOff1
go test -race -run TestExpBackOff2
go test -race -run TestWindow1
go test -race -run TestWindow2
go test -race -run TestWindow3
go test -race -run TestWindow4
go test -race -run TestWindow5
go test -race -run TestWindow6
go test -race -run TestOutOfOrderMsg1
go test -race -run TestOutOfOrderMsg2
go test -race -run TestOutOfOrderMsg3
go test -race -run TestServerSlowStart1
go test -race -run TestServerSlowStart2
go test -race -run TestServerClose1
go test -race -run TestServerClose2
go test -race -run TestServerCloseConns1
go test -race -run TestServerCloseConns2
go test -race -run TestClientClose1
go test -race -run TestClientClose2
go test -race -run TestServerFastClose1
go test -race -run TestServerFastClose2
go test -race -run TestServerFastClose3
go test -race -run TestServerToClient1
go test -race -run TestServerToClient2
go test -race -run TestServerToClient3
go test -race -run TestClientToServer1
go test -race -run TestClientToServer2
go test -race -run TestClientToServer3
go test -race -run TestRoundTrip1
go test -race -run TestRoundTrip2
go test -race -run TestRoundTrip3
go test -race -run TestVariableLengthMsgServer
go test -race -run TestVariableLengthMsgClient
go test -race -run TestCorruptedMsgServer
go test -race -run TestCorruptedMsgClient
